const IMAGES = {
    LOAD: 'IMAGES_LOAD',
    LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    LOAD_FAIL: 'IMAGES_LOAD_FAIL',
    PAGE: 'IMAGES_PAGE',
};

const STATS = {
    LOAD: 'STATS_LOAD',
    LOAD_SUCCESS: 'STATS_LOAD_SUCCESS',
    LOAD_FAIL: 'STATS_LOAD_FAIL',
};

const DETAIL = {
    LOAD: 'DETAIL_LOAD',
    LOAD_SUCCESS: 'DETAIL_LOAD_SUCCESS',
    LOAD_FAIL: 'DETAIL_LOAD_FAIL',
};

const MOVIES = {
    LOAD: 'MOVIES_LOAD',
    LOAD_SUCCESS: 'MOVIES_LOAD_SUCCESS',
    LOAD_FAIL: 'MOVIES_LOAD_FAIL',
};
const MOVIES_DETAIL = {
    LOAD: 'MOVIES_DETAIL_LOAD',
    LOAD_SUCCESS: 'MOVIES_DETAIL_LOAD_SUCCESS',
    LOAD_FAIL: 'MOVIES_DETAIL_LOAD_FAIL',
};

const CONFIG = {
  LOAD: 'CONFIG_LOAD',
  LOAD_SUCCESS: 'CONFIG_LOAD_SUCCESS',
};

export {
  IMAGES,
  STATS,
  DETAIL,
  MOVIES,
  MOVIES_DETAIL,
  CONFIG,
};
