const REGISTER = {
    REQUEST : 'REGISTER_REQUEST',
    SUCCESS : 'REGISTER_SUCCESS',
    FAIL : 'REGISTER_FAIL'
};
const LOGIN = {
    REQUEST : 'LOGIN_REQUEST',
    SUCCESS : 'LOGIN_SUCCESS',
    FAIL : 'LOGIN_FAIL'
};

export {
  REGISTER,
  LOGIN
};
